### PR TITLE
Public struct elements and defaults

### PR DESCRIPTION
**Pull request by gustavla**
I have been battle testing things in the last day or so (I have been developing a Rust port of `ddls` from https://github.com/uchicago-cs/deepdish, which basically gives you a nice-looking version of `h5ls`) and discovered more things that needed canging:
- The elements of all the structs clearly need to be public.
- Many of the API calls change structs in-place, so it's convenient to be able to create "empty" defaults that can then be filled.

I have tried to implement the `Default` trait for most of them. Usually, this can be done automatically, but the ones with pointers I have had to resort to doing it manually. The ones with function pointers I have left out, since they don't really need defaults anyway.

The `new_as_default!` macro means instead of `X { ..Default::default() }` you can just do `X::new()`. This is not essential, so if you don't like it I can take it out.

A few minor fixes are also included in this PR.

I have noticed that after these PRs, you usually have a series of really good tweaks. If you want, feel free to point things out and I'll change things, so as to make them part of the this PR and its discussion.

### CODE REVIEW

**Comment by IvanUkhov** [comment]
Hi Gustav,

I absolutely agree that all the fields should be public. Regarding “empty” defaults, I usually do something like this:

``` rust
let mut raw = unsafe { std::mem::zeroed() };
ffi::process(&mut raw);
```

This, however, requires `unsafe`, which not everybody likes. So perhaps `Default::default` is a more Rusty way of achieving this.

Thanks for your work!

Best,
Ivan

**Comment by gustavla** [comment]
I knew it was possible with unsafe, but `mem::zeroed` actually makes it simpler than what I had in mind for that. In that case I'm actually sort of on the fence about `Default`, but I think it's probably fine as it is now.

Thanks for merging!

**Comment by IvanUkhov** [comment]
@gustavla, on second thought, calling an FFI function will require `unsafe` anyway. Maybe elaborate defaults are no needed; just those that can be implemented with a simple `#[derive(Default)]`. Is this `zeroed`-based of technique suitable for your use case? I’d rather delete than keep what won’t be used; it’s a `-sys` crate after all.

Regards,
Ivan

**Comment by gustavla** [comment]
I agree. I have been trying out the `mem::zeroed`, and I think it is definitely the way to go here, instead of introducing all these arbitrary defaults. I think it applies to both structs and enums. It basically means reverting most of this PR, except for the small fixes and the elements made public. Sorry about that! I'd be happy to start working on a clean-up commit.

**Comment by gustavla** [comment]
Actually, you can probably just revert back to 39012ce. That should do it.

**Comment by IvanUkhov** [comment]
No worries at all! Making fields public was essential. Besides, deleting code is always a pleasure) Thanks again!

Regards,
Ivan

**Pull request merged**
